### ISSUE TITLE
PinCodeControl with scrollview

### ISSUE THREAD

**Issue by SE250880** [FreakyAli/Maui.FreakyControls#132] opened 2024-06-03 09:51 UTC
I use your Pincodecontrol in iOS with the latest release and fix KeyboardButtonHeightRequest. Due to space constraints on IPhone in landscape format I have to use a scrollview to enter the pin. But it does not work. The view is not scrollable and the buttons click does not work for all numbers, cancel and backspace button.

**Comment by FreakyAli** [comment] 2024-06-03 12:28
Add some relevant code

**Comment by SE250880** [comment] 2024-06-04 05:09
Ok, here is the code. I put your control in a grid to get some space around it.

<ScrollView>
    <Grid  Margin="0,0,0,5">
        <Grid.RowDefinitions>
            <RowDefinition Height="0.3*" />
            <RowDefinition Height="0.4*" />
            <RowDefinition Height="0.3*" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="0.1*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="0.1*" />
        </Grid.ColumnDefinitions>

        <Label Grid.Row="0" Grid.Column="0" Margin="20" Grid.ColumnSpan="3" FontSize="Large"  HorizontalOptions="Center"   VerticalOptions="End" HorizontalTextAlignment="Center"     Text="🔐 PIN-Code:" />

        <freakyControls:FreakyPinCodeControl
             x:Name="pinCodeCtrl"
             Grid.Row="1"               
             Grid.Column="1"
             BackspaceButtonSource="backspace.png"
             CancelClicked="FreakyPinCodeControl_CancelClicked"
             CodeLength="4"
             FontSize="Large"              
             ItemBackgroundColor="{StaticResource BGTransparent}"
             ItemBorderColor="White"
             ItemFocusAnimation="Scale"
             ItemShape="Circle"                 
             ItemSize="50"
             ItemBorderWidth="1"     
             ItemSpacing="30"
             KeyboardTextColor="Blue"
             HorizontalOptions="Center"             
             KeyboardSpacing="30"               
             KeyboardButtonHeightRequest="60"
             KeyboardButtonWidthRequest="60"            
             KeyboardButtonCornerRadius="20"
             KeyboardBackgroundColor="{StaticResource BGTransparent}"       
             CancelBackgroundColor="{StaticResource BGTransparent}"                
             BackspaceBackgroundColor="{StaticResource BGTransparent}"       
             CodeEntryCompleted="FreakyPinCodeControl_CodeEntryCompleted"                       
             CancelButtonText="X">
        </freakyControls:FreakyPinCodeControl>
    </Grid>
</ScrollView>

![grafik](https://github.com/FreakyAli/Maui.FreakyControls/assets/34155651/93fca655-7144-460a-803d-d2a6ef4dcca5)

On IPhone the last keyboard row doesn´t work like expected. An in landscape mode it doesn´t scroll.

**Comment by FreakyAli** [comment] 2024-06-04 05:35
Where is the scroll view?

**Comment by SE250880** [comment] 2024-06-04 05:36
Sorry, in the preview the code is cutted. So here is a printscreen:

![grafik](https://github.com/FreakyAli/Maui.FreakyControls/assets/34155651/a9b060d4-eed2-4f8b-b332-c49a65d6ca00)

**Comment by FreakyAli** [comment] 2024-06-05 12:19
I cannot replicate this, can you create a sample that can reproduce this...

Also, I have never really seen a pin-code control that can go landscape are you sure you want your user to have this option

**Comment by SE250880** [comment] 2024-06-06 10:45
Yes, my app also needs the pin code in landscape format.
I found a solution for myself by adjusting the row definition. I suspect this is a bug related to size *.
![grafik](https://github.com/FreakyAli/Maui.FreakyControls/assets/34155651/2ec7da4d-711d-4d37-bafa-4fd174e1573f)

**Comment by FreakyAli** [comment] 2024-06-07 09:53
What should be done with this bug in that case

**Comment by FreakyAli** [comment] 2024-06-12 05:51
Assuming this was not a bug with the control, but a design flaw I am going to close this bug, feel free to reopen in case of future issues!

**Closed by FreakyAli** 2024-06-12 05:51 UTC
Labels: question
